# Generated by Django 2.0.7 on 2018-07-28 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID Conekta')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre visible en la tarjeta')),
                ('bin', models.CharField(max_length=10)),
                ('brand', models.CharField(choices=[('AMERICAN_EXPRESS', 'American Express'), ('VISA', 'Visa'), ('MC', 'Master Card')], max_length=10, verbose_name='Tipo de tarjeta')),
                ('exp_month', models.CharField(max_length=2, verbose_name='Mes de expiración')),
                ('exp_year', models.CharField(max_length=2, verbose_name='Año de expiración')),
                ('last4', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos de la tarjeta')),
                ('default', models.BooleanField(help_text='Todos los cargos se hacen automáticamente a la tarjeta default del cliente', verbose_name='Tarjeta default')),
            ],
            options={
                'verbose_name': 'Tarjeta de crédito',
                'verbose_name_plural': 'Tarjetas de crédito',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Conekta Id')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('user', models.OneToOneField(help_text='Once created, it can not be modified', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.SlugField(help_text='Una vez creado no puede ser editado', max_length=80, primary_key=True, serialize=False, unique=True, verbose_name='Id de referencia')),
                ('name', models.CharField(max_length=600, verbose_name='Nombre del paquete')),
                ('currency', models.CharField(choices=[('MXN', 'Peso mexicano: MXN'), ('USD', 'Dólar americano: USD')], help_text='Una vez creado no puede ser editado', max_length=3, verbose_name='Moneda')),
                ('amount', models.IntegerField(verbose_name='Precio')),
                ('frequency', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1, help_text='Una vez creado no puede ser editado', verbose_name='Frecuencia')),
                ('interval', models.CharField(choices=[('minute', 'Minuto'), ('week', 'Semana'), ('half_month', 'Quincena'), ('month', 'Mes'), ('year', 'Año')], default='month', help_text='Una vez creado no puede ser editado', max_length=50, verbose_name='Intervalo de pago')),
                ('trial_period_days', models.IntegerField(default=30, help_text='Una vez creado no puede ser editado', verbose_name='Días de prueba')),
                ('expiry_count_mode', models.CharField(choices=[('forever', 'Indefinido'), ('fixed', 'Fijo')], default='forever', help_text='Una vez creado no puede ser editado', max_length=10, verbose_name='Duración')),
                ('expiry_count', models.IntegerField(blank=True, help_text="Solo aplica con el modo de cobro 'Fijo'. Una vez creado no puede ser editado", null=True, verbose_name='Número de repeticiones')),
                ('is_visible', models.BooleanField(default=False, verbose_name='¿Visible?')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='¿Recomendado?')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True, verbose_name='ID Conekta')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pausado')),
                ('trial_start', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio del periodo de prueba')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin del periodo de prueba')),
                ('subscription_start', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de suscripción')),
                ('status', models.CharField(blank=True, choices=[('in_trial', 'En trial'), ('active', 'Active'), ('past_due', 'Vencido'), ('paused', 'Pausado'), ('canceled', 'Cancelado')], max_length=10, null=True, verbose_name='Estatus')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conektango.Customer', verbose_name='Cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conektango.Plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conektango.Customer', verbose_name='Cliente'),
        ),
    ]
