# Generated by Django 2.0.7 on 2018-07-20 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID Conekta')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarjeta de crédito',
                'verbose_name_plural': 'Tarjetas de crédito',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID Conekta')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False, unique=True, verbose_name='Id de referencia')),
                ('name', models.CharField(max_length=600, verbose_name='Nombre del paquete')),
                ('currency', models.CharField(choices=[('MXN', 'Peso mexicano: MXN'), ('USD', 'Dólar americano: USD')], max_length=3, verbose_name='Moneda')),
                ('amount', models.IntegerField(verbose_name='Precio')),
                ('frequency', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1, verbose_name='Frecuencia')),
                ('interval', models.CharField(choices=[('minute', 'Minuto'), ('week', 'Semana'), ('half_month', 'Quincena'), ('month', 'Mes'), ('year', 'Año')], default='month', max_length=50, verbose_name='Frecuencia de pago')),
                ('trial_period_days', models.IntegerField(default=30, verbose_name='Días de prueba')),
                ('expiry_count_mode', models.CharField(choices=[('forever', 'Indefinido'), ('fixed', 'Fijo')], default='forever', max_length=10, verbose_name='Duración')),
                ('expiry_count', models.IntegerField(blank=True, help_text="Solo aplica con el modo de cobro 'Fijo'", null=True, verbose_name='Número de repeticiones')),
                ('is_visible', models.BooleanField(default=False, verbose_name='¿Visible?')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='¿Recomendado?')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True, verbose_name='ID Conekta')),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación')),
                ('canceled_at', models.DateTimeField(verbose_name='Fecha de creación')),
                ('paused_at', models.DateTimeField(verbose_name='Fecha de creación')),
                ('trial_start', models.DateTimeField(verbose_name='Fecha de inicio del periodo de prueba')),
                ('trial_end', models.DateTimeField(verbose_name='Fecha de fin del periodo de prueba')),
                ('status', models.CharField(max_length=10, verbose_name='Estatus')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conektango.CreditCard', verbose_name='Tarjeta de Crédito')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conektango.Customer', verbose_name='Cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conektango.Plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
            },
        ),
    ]
