# Generated by Django 2.0.7 on 2018-07-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conektango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='default',
            field=models.BooleanField(help_text='Todos los cargos se hacen automáticamente a la tarjeta default del cliente', verbose_name='Tarjeta default'),
        ),
    ]
